添加对yaml的支持，解析器抽象化
ZhengHe-MD/agollo pull request #2
Opened 2021-07-06 12:24 UTC by EAHITechnology

2021-07-06 13:00 UTC, ZhengHe-MD requested changes

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +	intSlices := []int{}
```go
intSlices := make([]int, len(intSliceIfVal))
```

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +func (c *Client) GetYmlContent(val interface{}) {
这个是刻意放空吗？ exposed method 最好不要这么搞

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +	return c.GetStringWithNamespace(namespace, string(namespaceTyp)+"content")
这里的 `string(namespaceTyp) + "content"` 是在做什么事情？

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +	content, ok := c.GetStringWithNamespace(namespace, string(namespaceTyp)+"content")
看着貌似这里可以直接调用 `c.GetNamespaceContent`？

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +	otherNamespaceTyp namespaceTyp = ""
`defaultNamespaceTyp` 或者 `emptyNamespaceTyp`

other 后面一般跟的是复数 `otherNamespaceTyps`，放这里似乎不太合适。

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +		if err != nil {
这里可能得打 error 日志。另外是否需要 fail-fast？指定了配置文件类型，解析失败或解析出来为 nil，这件事情是不是应该让用户知道

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +		newConfigurations[content+"content"] = val
我感觉应该写一个 `getRawContentKey` 或 `genRawContentKey` 的方法，不要在很多个地方手动拼装。

2021-07-06 13:00 UTC, ZhengHe-MD commented on parse/normal/parser.go
> +package normal
这个 normal parser 有在哪里被使用吗？

2021-07-06 13:00 UTC, ZhengHe-MD commented on parse/parser.go
> +	default:
这边不需要 properties Parser 吗？

2021-07-06 13:00 UTC, ZhengHe-MD commented on parse/properties/parser.go
> +// Parser properties转换器
这里如果有注释，其它 Parser 也应该有注释。另外，中英文之间需要用空格间隔开

2021-07-06 13:00 UTC, ZhengHe-MD commented on parse/yaml/parser.go
> +	if "" == content {
一般会把变量放左边，常量放右边。我觉得没有特殊理由，按 Go 社区和源码的习惯来吧~

2021-07-06 13:00 UTC, ZhengHe-MD commented on parse/yml/parser.go
> +	if "" == content {
同上

2021-07-06 13:00 UTC, ZhengHe-MD commented on client.go
> +	if err := parser.Unmarshal([]byte(content), val); err != nil {
上面的 GetParser 可能会返回 nil，这里是不是就 panic 了？

2021-07-06 13:01 UTC, ZhengHe-MD commented on client.go
> +	return c.GetStringWithNamespace(namespace, string(namespaceTyp)+"content")
大概从地下的代码中理解了，可以忽略这个 comment，看后面的评论

2021-07-06 13:03 UTC, EAHITechnology commented on client.go
> +	otherNamespaceTyp namespaceTyp = ""
这里我修改一下

2021-07-06 13:04 UTC, EAHITechnology commented on parse/properties/parser.go
> +// Parser properties转换器
好的

2021-07-06 13:04 UTC, EAHITechnology commented on parse/yaml/parser.go
> +	if "" == content {
好的

2021-07-07 03:04 UTC, EAHITechnology commented on parse/yaml/parser.go
> +	if "" == content {
这是以前cpp的一个小习惯跟过来的，用 if 判断一个变量和一个常量是否相等时，都会把常量写在右边，但如果一不小心笔误漏了一个 ‘=’ 号，结果该语句得不到执行机会，属于运行错误，很难被发现。但是如果我们把常量写在左边， 那么编译器立即指示这个编译错误（Lvalue Error）。但是在golang中有被很好的处理这种错误这里我先改过来

2021-07-09 07:04 UTC, ZhengHe-MD approved these changes

2021-07-09 07:04 UTC, merged